print('Test config:')
print('- 20 concurrent clients')
print('- 5 servers')
print('- Zipf alpha=2.5 (highly skewed)')
print('')
print('Average load:', 20/5, 'connections/server')
print('')
print('With capacity_factor:')
for cf in [1.25, 2.0, 2.5, 3.0, 4.0, 5.0]:
    print(f'  {cf}: threshold = {(20/5)*cf:.1f} connections')
print('')
print('With Zipf 2.5, top server might get 40-50% of traffic')
print('That is 8-10 concurrent connections')
print('')
print('Needed capacity_factor: 10/4 = 2.5 (minimum)')
print('But with variance, need 3.0-4.0 for safety')
